import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppMori = localFont({
  src: [
    { path: "./fonts/PPMori-Extralight.otf", weight: "200", style: "normal" },
    { path: "./fonts/PPMori-ExtralightItalic.otf", weight: "200", style: "italic" },
    { path: "./fonts/PPMori-Regular.otf", weight: "400", style: "normal" },
    { path: "./fonts/PPMori-RegularItalic.otf", weight: "400", style: "italic" },
    { path: "./fonts/PPMori-SemiBold.otf", weight: "600", style: "normal" },
    { path: "./fonts/PPMori-SemiBoldItalic.otf", weight: "600", style: "italic" },
  ],
  variable: "--font-pp-mori",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ppMori.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-sans">{children}</body>
    </html>
  );
}